DJANGO_PDV/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls.static import static
from django.conf import settings

from catalogo import views
from inventario import views as inventario_views
from punto_de_venta import views as puntodeventa_views
from pedidos_pendientes import views as pedidospendientes_views
from users import views as user_views


urlpatterns = [
    path('generar_pdf/', inventario_views.generar_pdf, name='generar_pdf'),
    path('admin/', admin.site.urls),

    #path('signup/', user_views.signup, name='signup'),
    path('logout/', user_views.signout, name='logout'),
    path('', user_views.signin, name='signin'),
    
    path('catalogo/', views.catalogo, name='catalogo'),
    path('inventario/', inventario_views.inventario, name='inventario'),
    path('puntodeventa/', puntodeventa_views.punto_de_venta, name='puntodeventa'),
    path('pedidospendientes/', pedidospendientes_views.pedidos_pendientes, name='pedidospendientes')
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

catalogo/models.py
from django.db import models

categorias = [
    [0, 'Comunicacion'],
    [1, 'Seguridad'],
    [2, 'Educacion'],
    [3, 'Microcontroladores'],
    [4, 'Accesorios']
]
niveles = [
    [0, 'Nivel 1'],
    [1, 'Nivel 2'],
    [3, 'Nivel 3']
]
secciones = [
    [0, 'Rack A'],
    [1, 'Rack B'],
    [2, 'Rack C'],
    [3, 'Rack D'],
    [4, 'Rack E'],
    [5, 'Rack F'],
    [6, 'Rack G'],
    [7, 'Rack H']
]
class Producto(models.Model):
    imagen = models.ImageField(upload_to='catalogo/images/')
    nombre = models.CharField(max_length=250)
    descripcion = models.TextField(max_length=999)
    numero_De_Pieza = models.CharField(max_length=100)
    precio = models.CharField(max_length=51)

    existencias = models.IntegerField()
    conteo_Fisico = models.IntegerField()

    categoria = models.IntegerField(choices=categorias)
    nivel = models.IntegerField(choices=niveles)
    seccion = models.IntegerField(choices=secciones)

    def __str__(self):
        return self.nombre
    
class filtros(models.Model):
    todos = models.BooleanField(default=False)
    comunicacion = models.BooleanField(default=False)
    seguridad = models.BooleanField(default=False)
    educacion = models.BooleanField(default=False)
    microcontroladores = models.BooleanField(default=False)
    accesorios = models.BooleanField(default=False)

inventario/models.py
from django.db import models

# Create your models here.

inventario/views.py
from django.shortcuts import render, redirect
from catalogo.models import Producto
from django.http import HttpResponse
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle
from catalogo.models import Producto,categorias, niveles, secciones
import datetime

now = datetime.datetime.now()
now = now.strftime("%d-%m-%Y")

secciones = {0: 'Rack A', 1: 'Rack B', 2: 'Rack C', 3: 'Rack D', 4: 'Rack E', 5: 'Rack F', 6: 'Rack G', 7: 'Rack H'}
categorias = {0: 'Comunicacion', 1: 'Seguridad', 2: 'Educacion', 3: 'Microcontroladores', 4: 'Accesorios'}
niveles = {0: 'Nivel 1', 1: 'Nivel 2', 3: 'Nivel 3'}

def generar_pdf(request):
    if request.user.is_authenticated:
        # Obtener los productos de la base de datos
        productos = Producto.objects.all()
        # Crear un documento PDF
        response = HttpResponse(content_type='application/pdf')
        response['Content-Disposition'] = f'attachment; filename="reporte_inventario_{now}.pdf"'
        document = SimpleDocTemplate(response, pagesize=letter)
        # Crear los datos para la tabla
        data = [['Nombre', 'Número de Pieza', 'Existencias', 'Conteo Físico', 'Categoría', 'Nivel', 'Sección']]
        for producto in productos:
            categoria_texto = categorias.get(producto.categoria, 'Categoría Desconocida')
            nivel_texto = niveles.get(producto.nivel, 'Nivel Desconocido')
            seccion_texto = secciones.get(producto.seccion, 'Sección Desconocida')
            data.append([
                producto.nombre,
                producto.numero_De_Pieza,
                producto.existencias,
                producto.conteo_Fisico,
                categoria_texto,
                nivel_texto,
                seccion_texto
            ])
        # Crear una instancia de la tabla
        table = Table(data)
        # Aplicar estilos a la tabla
        style = TableStyle([('BACKGROUND', (0, 0), (-1, 0), colors.grey),
                            ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
                            ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
                            ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
                            ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
                            ('BACKGROUND', (0, 1), (-1, -1), colors.beige),
                            ('GRID', (0, 0), (-1, -1), 1, colors.black)])
        table.setStyle(style)
        # Construir el PDF
        content = [table]
        document.build(content)
        return response
    else:
        return redirect('signin')
    

def inventario(request):
    if request.user.is_authenticated:
        producto_inventario = Producto.objects.all()
        return render(request, 'inventario.html', {'productos_inventario': producto_inventario})
    else:
        return redirect('signin')

inventario/templates/inventario.html
{% extends 'layout.html' %}

{% block content %}
    <div class="text-center">
        <h2 class="text-light">Inventario</h2>
        <a href="{% url 'generar_pdf' %}" class="btn btn-dark mx-auto">Descargar inventario</a>
    </div>
    <div class="row my-4 text-center">
        <table class="table table-striped text-light">
            <tr>
                <th scope="col">Referencia</th>
                <th scope="col">Nombre</th>
                <th scope="col">Numero de pieza</th>
                <th scope="col">Existencias</th>
                <th scope="col">Conteo fisico</th>
                <th scope="col">Categoria</th>
                <th scope="col">Nivel</th>
                <th scope="col">Seccion</th>
            </tr>
            {% for producto in productos_inventario %}
                <tr>
                    <td scope="row">
                        <img class="img-fluid" src="{{producto.imagen.url}}" alt="Imagen del Producto" width="100em">
                    </td>
                    <td scope="row">{{producto.nombre}}</td>
                    <td scope="row">{{producto.numero_De_Pieza}}</td>
                    <td scope="row">{{producto.existencias}}</td>
                    <td scope="row">{{producto.conteo_Fisico}}</td>
                    <td scope="row">{{producto.nivel}}</td>
                    <td scope="row">{{ producto.get_seccion_display }}</td>
                    <td scope="row">{{producto.get_categoria_display}}</td>
                  </tr>
            {% endfor %}
        </table>
    </div>
{% endblock  %}